# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-kr
  contentDir: content/ko
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: KJH Portfolio
  params:
    description: KimJaeHyeon Portfolio
  menus:
    main:
      - name: PROFILE
        url: profile
        weight: 10
        identifier: profile
      - name: PROFILE
        parent: profile
        url: /
        weight: 11

      - name: SKILLS
        parent: profile
        url: /#skills
        weight: 12

      - name: CONTACT
        url: /#contact
        weight: 50

      - name: ACTIVITY
        url: activity/
        weight: 25
        identifier: activity

      - name: STUDY
        parent: activity
        url: /activity/studing/
        weight: 26

      - name: CODING
        parent: activity
        url: /activity/coding/
        weight: 27

      - name: PROJECT
        url: project/
        identifier: project
        weight: 30

      - name: EXPERIENCE
        url: experience/
        weight: 40
