main:
  - name: 프로필
    url: profile
    weight: 10
    identifier: profile
  - name: 프로필
    parent: profile
    url: /
    weight: 11

  - name: 기술
    parent: profile
    url: /#skills
    weight: 12

  - name: 연락
    url: /#contact
    weight: 50

  - name: 활동
    url: activity/
    weight: 25
    identifier: activity

  - name: 공부
    parent: activity
    url: /activity/studing/
    weight: 26

  - name: 알고리즘
    parent: activity
    url: /activity/coding/
    weight: 27

  - name: 프로젝트
    url: projects/
    identifier: projects
    weight: 30

  - name: 학교
    url: experience/
    weight: 40
